disabled_rules:

    # 비활성화하고 싶은 규칙
    
    - identifier_name
    - line_length
    - type_name
    - legacy_constructor
    - unused_setter_value
    - void_function_in_ternary
    - nesting
    - comment_spacing
    - cyclomatic_complexity

opt_in_rules:
    - function_parameter_count
    - function_body_length
    - trailing_whitespace
    - empty_count
    - empty_string
    - closure_end_indentation
    - let_var_whitespace
    - explicit_enum_raw_values
    - unused_import

included:
    - 37-COLLABORATION-UNIQLO
excluded:
    - 37-COLLABORATION-UNIQLO/Core/AppDelegate.swift
    - 37-COLLABORATION-UNIQLO/Core/SceneDelegate.swift
